/**
 * Python Master - Rascacielos Digital
 * 
 * Agente maestro especializado en Python con integración Ollama
 */

const OllamaClient = require('../../modules/ollama-client');

class PythonMaster {
  constructor(config = {}) {
    this.config = {
      verbose: config.verbose || false,
      ...config
    };

    // Ollama integration
    this.useOllama = config.useOllama || false;
    this.ollama = this.useOllama
      ? new OllamaClient({
          model: config.ollamaModel || 'codellama',
          baseURL: config.ollamaURL || 'http://localhost:11434'
        })
      : null;
  }

  /**
   * Analizar código Python
   */
  async analyze(code, options = {}) {
    // Análisis básico (rápido)
    const basicAnalysis = await this._basicAnalyze(code);

    // Si Ollama está habilitado, análisis profundo con LLM
    if (this.useOllama && options.deep) {
      try {
        const llmAnalysis = await this.ollama.analyzeCode(
          code,
          'python',
          'Focus on type hints, async/await usage, and PEP 8 compliance'
        );

        return {
          ...basicAnalysis,
          llmInsights: llmAnalysis,
          enhanced: true
        };
      } catch (error) {
        console.warn('Ollama analysis failed, using basic:', error.message);
        return basicAnalysis;
      }
    }

    return basicAnalysis;
  }

  /**
   * Generar scaffold de proyecto
   */
  async scaffold(projectType, options = {}) {
    // Si Ollama está habilitado, generar con LLM
    if (this.useOllama && options.useAI) {
      try {
        const aiScaffold = await this.ollama.generateScaffold(
          projectType,
          'python',
          options
        );

        return {
          files: this._parseScaffoldResponse(aiScaffold),
          generatedBy: 'ollama-' + this.ollama.model
        };
      } catch (error) {
        console.warn(
          'Ollama scaffold failed, using templates:',
          error.message
        );
      }
    }

    // Fallback a templates
    return this._scaffoldFastAPI(options);
  }

  /**
   * Detectar issues en código
   */
  async detectIssues(code) {
    const basicIssues = await this._basicDetectIssues(code);

    if (this.useOllama) {
      try {
        const securityIssues = await this.ollama.detectSecurityIssues(
          code,
          'python'
        );
        return [...basicIssues, ...(securityIssues.vulnerabilities || [])];
      } catch (error) {
        return basicIssues;
      }
    }

    return basicIssues;
  }

  /**
   * Optimizar código Python
   */
  async optimize(code) {
    if (this.useOllama) {
      try {
        return await this.ollama.optimizeCode(code, 'python');
      } catch (error) {
        console.warn('Ollama optimization failed:', error.message);
      }
    }

    // Fallback: retornar código original si no hay Ollama
    return code;
  }

  /**
   * Análisis básico de código Python
   */
  async _basicAnalyze(code) {
    const issues = [];
    const metrics = {
      lines: code.split('\n').length,
      functions: (code.match(/def\s+\w+/g) || []).length,
      classes: (code.match(/class\s+\w+/g) || []).length
    };

    // Detectar imports faltantes
    if (code.includes('asyncio') && !code.includes('import asyncio')) {
      issues.push({
        type: 'missing_import',
        severity: 'high',
        message: 'asyncio used but not imported'
      });
    }

    // Detectar docstrings faltantes
    const functionMatches = code.match(/def\s+\w+[^:]*:/g) || [];
    functionMatches.forEach((func) => {
      const funcIndex = code.indexOf(func);
      const nextLines = code.substring(funcIndex).split('\n').slice(0, 3);
      const hasDocstring = nextLines.some((line) => line.includes('"""'));
      if (!hasDocstring) {
        issues.push({
          type: 'missing_docstring',
          severity: 'low',
          message: `Function ${func} missing docstring`
        });
      }
    });

    return {
      metrics,
      issues,
      enhanced: false
    };
  }

  /**
   * Scaffold básico FastAPI
   */
  async _scaffoldFastAPI(options = {}) {
    const projectName = options.name || 'my-fastapi-app';

    return {
      files: {
        'main.py': `"""
${projectName} - FastAPI Application
"""
from fastapi import FastAPI

app = FastAPI(title="${projectName}")

@app.get("/")
async def root():
    return {"message": "Hello from ${projectName}"}

@app.get("/health")
async def health():
    return {"status": "healthy"}
`,
        'requirements.txt': `fastapi>=0.109.0
uvicorn[standard]>=0.27.0
pydantic>=2.5.0
`,
        'README.md': `# ${projectName}

FastAPI application generated by Rascacielos Digital

## Setup
\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Run
\`\`\`bash
uvicorn main:app --reload
\`\`\`
`
      },
      generatedBy: 'template'
    };
  }

  /**
   * Detectar issues básicos
   */
  async _basicDetectIssues(code) {
    const issues = [];

    // Detectar uso de eval
    if (code.includes('eval(')) {
      issues.push({
        type: 'dangerous_function',
        severity: 'critical',
        description: 'Use of eval() is dangerous',
        fix: 'Use ast.literal_eval() or safer alternatives'
      });
    }

    // Detectar SQL injection potencial
    if (
      code.includes('execute(') &&
      code.match(/execute\([^)]*%s[^)]*\)/) === null &&
      code.match(/execute\([^)]*f["'][^"']*\{[^}]*\}/)
    ) {
      issues.push({
        type: 'sql_injection',
        severity: 'high',
        description: 'Potential SQL injection vulnerability',
        fix: 'Use parameterized queries'
      });
    }

    return issues;
  }

  /**
   * Parse respuesta de scaffold de Ollama
   */
  _parseScaffoldResponse(response) {
    // Intentar extraer archivos del response
    const files = {};

    // Buscar bloques de código con nombres de archivo
    const filePattern = /```(\w+)\s*(?:\/\/|#)\s*([^\n]+)\n([\s\S]*?)```/g;
    let match;

    while ((match = filePattern.exec(response)) !== null) {
      const [, , filename, content] = match;
      files[filename.trim()] = content.trim();
    }

    // Si no hay archivos detectados, retornar el response completo
    if (Object.keys(files).length === 0) {
      files['generated.py'] = response;
    }

    return files;
  }
}

module.exports = PythonMaster;
